name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:1.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build gem
        run: gem build asciidoctor-lists.gemspec

      - name: Rename gem
        run: mv asciidoctor-lists-*.gem asciidoctor-lists.gem

      - name: Install gem
        run: gem install asciidoctor-lists.gem

      - name: Build list-sample as PDF
        run: asciidoctor-pdf -a allow-uri-read -r asciidoctor-lists samples/list-sample.adoc

      - name: Build enhanced-rendering as PDF
        run: asciidoctor-pdf -a allow-uri-read -r asciidoctor-lists samples/enhanced-rendering.adoc

      - name: Build hide-if-empty-list-sample as PDF
        run: asciidoctor-pdf -a allow-uri-read -r asciidoctor-lists samples/hide-if-empty-list-sample.adoc

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: samples
          path: samples

